// ESM translations module
export const translations = {
  cs: {
    title: "Občanská iniciativa za sjednocení Československa",
    nav: { logo: "Nové Československo", home: "Domů", about: "O iniciativě", events: "Akce", business: "Podnikání", news: "Novinky", contact: "Zapojit se" },
    home: { title: "Nové Československo", subtitle: "Iniciativa za sjednocení Československa", learn_more: "Zjistit více", get_involved: "Zapojit se", features: { cooperation: { title: "Přeshraniční spolupráce", description: "Podporujeme projekty spojující české a slovenské občany" }, culture: { title: "Kulturní dědictví", description: "Oslavujeme společnou historii a tradice našich národů" }, business: { title: "Obchodní příležitosti", description: "Vytváříme platformu pro podnikatelskou spolupráci" } } },
    about: { title: "Vize iniciativy Nové Československo", subtitle: "Československo neskončilo", opening: { paragraph1: "...", paragraph2: "..." }, vision: { title: "🎯 Krok za krokem k společnému státu", text: "..." }, beliefs: { title: "💡 Čemu věříme", partnership: "V přirozené partnerství mezi Čechy a Slováky", connection: "V propojení kultur, vzdělávání, podnikání i sportu", initiative: "V sílu občanské iniciativy, která předbíhá politická rozhodnutí", discussion: "V otevřenou diskusi o budoucnosti společného státu" }, goals: { title: "🛠️ Čeho chceme docílit", community: "Spájet příznivce a budujeme komunitu", events: "Organizovat veřejné akce, debaty a setkání", support: "Podporovat studenty, podnikatele, zaměstnance i umělce při přeshraničním působení", politics: "Vyzvat politické strany v Česku i na Slovensku, aby se témou sjednocení začali zabývat a k zaujetí jasného postoje" }, calltoaction: "Připojte se k nám!", slogan: "Nové Československo\nLepší spolu" },
    events: { title: "Nadcházející akce", subtitle: "Setkání, diskuse a kulturní události", months: { jan: "Led", feb: "Úno", mar: "Bře", apr: "Dub", may: "Kvě", jun: "Čer", jul: "Čvc", aug: "Srp", sep: "Zář", oct: "Říj", nov: "Lis", dec: "Pro" }, conference: { title: "Konference o budoucnosti", location: "Praha, Národní divadlo", description: "Diskuse o možnostech hlubší spolupráce mezi ČR a SR" }, cultural: { title: "Kulturní večer", location: "Bratislava, Reduta", description: "Společný koncert českých a slovenských umělců" }, business: { title: "Business forum", location: "Brno, Výstaviště", description: "Networking a podnikatelské příležitosti" } },
    business: { title: "Podnikání a spolupráce", subtitle: "Platforma pro rozvoj česko-slovenských obchodních vztahů", learn_more: "Zjistit více", startups: { title: "Startup accelerator", description: "Podporujeme inovativní projekty spojující oba trhy" }, manufacturing: { title: "Průmyslová spolupráce", description: "Síťování výrobních podniků a dodavatelů" }, education: { title: "Vzdělávací programy", description: "Výměnné stáže a společné projekty univerzit" }, innovation: { title: "Inovační centrum", description: "Společný výzkum a vývoj nových technologií" } },
    news: { title: "Aktuality", subtitle: "Nejnovější zprávy z našich aktivit", read_more: "Číst více", categories: { events: "Akce", business: "Podnikání", culture: "Kultura" }, featured: { title: "Úspěšná konference v Praze", excerpt: "Více než 500 účastníků diskutovalo o budoucnosti česko-slovenských vztahů" }, business: { title: "Nové partnerství mezi firmami", excerpt: "Podepsáno 15 nových smluv o spolupráci" }, culture: { title: "Kulturní výměna pokračuje", excerpt: "Nový program pro mladé umělce" } },
    contact: { title: "Zapojte se do iniciativy", subtitle: "Staňte se součástí našeho hnutí za lepší budoucnost", volunteer: { title: "Dobrovolnictví", description: "Pomozte nám organizovat akce a šířit myšlenku spolupráce", button: "Stát se dobrovolníkem" }, donate: { title: "Podpora", description: "Finančně podpořte naše aktivity a projekty", button: "Přispět" }, newsletter: { title: "Newsletter", description: "Získejte nejnovější informace o našich aktivitách", button: "Odebírat" }, info: { title: "Kontaktní informace", email: "Email", phone: "Telefon", address: "Adresa" } },
    footer: { about: { title: "O nás", text: "Občanská iniciativa za obnovu přirozených vazeb mezi Českou republikou a Slovenskem." }, links: { title: "Rychlé odkazy", about: "O iniciativě", events: "Akce", business: "Podnikání", contact: "Kontakt" }, contact: { title: "Kontakt" }, map: { title: "Historické Československo" }, rights: "Všechna práva vyhrazena." }
  },
  sk: {
    title: "Občianska iniciatíva za zjednotenie Československa",
    nav: { logo: "Nové Československo", home: "Domov", about: "O iniciatíve", events: "Akcie", business: "Podnikanie", news: "Novinky", contact: "Zapojiť sa" },
    home: { title: "Nové Československo", subtitle: "Iniciatíva za zjednotenie Československa", learn_more: "Zistiť viac", get_involved: "Zapojiť sa", features: { cooperation: { title: "Cezhraničná spolupráca", description: "Podporujeme projekty spájajúce českých a slovenských občanov" }, culture: { title: "Kultúrne dedičstvo", description: "Oslavujeme spoločnú históriu a tradície našich národov" }, business: { title: "Obchodné príležitosti", description: "Vytvárame platformu pre podnikateľskú spoluprácu" } } },
    about: { title: "Vízia iniciatívy Nové Československo", subtitle: "Československo neskončilo", opening: { paragraph1: "...", paragraph2: "..." }, vision: { title: "🎯 Krok za krokom k spoločnému štátu", text: "..." }, beliefs: { title: "💡 Čomu veríme", partnership: "V prirodzené partnerstvo medzi Čechmi a Slovákmi", connection: "V prepojenie kultúr, vzdelávania, podnikania i športu", initiative: "V silu občianskej iniciatívy, ktorá predbiehá politické rozhodnutia", discussion: "V otvorenú diskusiu o budúcnosti spoločného štátu" }, goals: { title: "🛠️ Čoho chceme dosiahnuť", community: "Spájať priaznivcov a budujeme komunitu", events: "Organizovať verejné akcie, debaty a stretnutia", support: "Podporovať študentov, podnikateľov, zamestnancov i umelcov pri cezhraničnom pôsobení", politics: "Vyzvať politické strany v Česku i na Slovensku, aby sa témou zjednotenia začali zaoberať a zaujali jasný postoj" }, calltoaction: "Pripojte sa k nám!", slogan: "Nové Československo\nLepšie spolu" },
    events: { title: "Nadchádzajúce akcie", subtitle: "Stretnutia, diskusie a kultúrne udalosti", months: { jan: "Jan", feb: "Feb", mar: "Mar", apr: "Apr", may: "Máj", jun: "Jún", jul: "Júl", aug: "Aug", sep: "Sep", oct: "Okt", nov: "Nov", dec: "Dec" }, conference: { title: "Konferencia o budúcnosti", location: "Praha, Národné divadlo", description: "Diskusia o možnostiach hlbšej spolupráce medzi ČR a SR" }, cultural: { title: "Kultúrny večer", location: "Bratislava, Reduta", description: "Spoločný koncert českých a slovenských umelcov" }, business: { title: "Business fórum", location: "Brno, Výstavisko", description: "Networking a podnikateľské príležitosti" } },
    business: { title: "Podnikanie a spolupráca", subtitle: "Platforma pre rozvoj česko-slovenských obchodných vzťahov", learn_more: "Zistiť viac", startups: { title: "Startup akcelerátor", description: "Podporujeme inovatívne projekty spájajúce oba trhy" }, manufacturing: { title: "Priemyselná spolupráca", description: "Sieťovanie výrobných podnikov a dodávateľov" }, education: { title: "Vzdelávacie programy", description: "Výmenné stáže a spoločné projekty univerzít" }, innovation: { title: "Inovačné centrum", description: "Spoločný výskum a vývoj nových technológií" } },
    news: { title: "Aktuality", subtitle: "Najnovšie správy z našich aktivít", read_more: "Čítať viac", categories: { events: "Akcie", business: "Podnikanie", culture: "Kultúra" }, featured: { title: "Úspešná konferencia v Prahe", excerpt: "Viac ako 500 účastníkov diskutovalo o budúcnosti česko-slovenských vzťahov" }, business: { title: "Nové partnerstvo medzi firmami", excerpt: "Podpísaných 15 nových zmlúv o spolupráci" }, culture: { title: "Kultúrna výmena pokračuje", excerpt: "Nový program pre mladých umelcov" } },
    contact: { title: "Zapojte sa do iniciatívy", subtitle: "Staňte sa súčasťou nášho hnutia za lepšiu budúcnosť", volunteer: { title: "Dobrovoľníctvo", description: "Pomôžte nám organizovať akcie a šíriť myšlienku spolupráce", button: "Stať sa dobrovoľníkom" }, donate: { title: "Podpora", description: "Finančne podporte naše aktivity a projekty", button: "Prispieť" }, newsletter: { title: "Newsletter", description: "Získajte najnovšie informácie o našich aktivitách", button: "Odoberať" }, info: { title: "Kontaktné informácie", email: "Email", phone: "Telefón", address: "Adresa" } },
    footer: { about: { title: "O nás", text: "Občianska iniciatíva za obnovu prirodzených väzieb medzi Českou republikou a Slovenskom." }, links: { title: "Rýchle odkazy", about: "O iniciatíve", events: "Akcie", business: "Podnikanie", contact: "Kontakt" }, contact: { title: "Kontakt" }, map: { title: "Historické Československo" }, rights: "Všetky práva vyhradené." }
  },
  en: {
    title: "Citizens' Initiative for Czechoslovak Reunification",
    nav: { logo: "New Czechoslovakia", home: "Home", about: "About", events: "Events", business: "Business", news: "News", contact: "Get Involved" },
    home: { title: "New Czechoslovakia", subtitle: "Initiative for Czechoslovak Reunification", learn_more: "Learn More", get_involved: "Get Involved", features: { cooperation: { title: "Cross-border Cooperation", description: "We support projects connecting Czech and Slovak citizens" }, culture: { title: "Cultural Heritage", description: "We celebrate the shared history and traditions of our nations" }, business: { title: "Business Opportunities", description: "We create a platform for entrepreneurial cooperation" } } },
    about: { title: "Vision of the New Czechoslovakia Initiative", subtitle: "Czechoslovakia never ended", opening: { paragraph1: "...", paragraph2: "..." }, vision: { title: "🎯 Step by step towards a common state", text: "..." }, beliefs: { title: "💡 What we believe in", partnership: "In natural partnership between Czechs and Slovaks", connection: "In connecting cultures, education, business, and sports", initiative: "In the power of civic initiative that precedes political decisions", discussion: "In open discussion about the future of a common state" }, goals: { title: "🛠️ What we want to achieve", community: "Unite supporters and build community", events: "Organize public events, debates, and meetings", support: "Support students, entrepreneurs, employees, and artists in cross-border activities", politics: "Call on political parties in Czechia and Slovakia to start addressing the topic of reunification and take a clear stance" }, calltoaction: "Join us!", slogan: "New Czechoslovakia\nBetter together" },
    events: { title: "Upcoming Events", subtitle: "Meetings, discussions, and cultural events", months: { jan: "Jan", feb: "Feb", mar: "Mar", apr: "Apr", may: "May", jun: "Jun", jul: "Jul", aug: "Aug", sep: "Sep", oct: "Oct", nov: "Nov", dec: "Dec" }, conference: { title: "Future Conference", location: "Prague, National Theatre", description: "Discussion on possibilities for deeper cooperation between CZ and SK" }, cultural: { title: "Cultural Evening", location: "Bratislava, Reduta", description: "Joint concert of Czech and Slovak artists" }, business: { title: "Business Forum", location: "Brno, Exhibition Centre", description: "Networking and business opportunities" } },
    business: { title: "Business & Cooperation", subtitle: "Platform for developing Czech-Slovak business relations", learn_more: "Learn More", startups: { title: "Startup Accelerator", description: "We support innovative projects connecting both markets" }, manufacturing: { title: "Industrial Cooperation", description: "Networking of manufacturing companies and suppliers" }, education: { title: "Educational Programs", description: "Exchange internships and joint university projects" }, innovation: { title: "Innovation Center", description: "Joint research and development of new technologies" } },
    news: { title: "News", subtitle: "Latest news from our activities", read_more: "Read More", categories: { events: "Events", business: "Business", culture: "Culture" }, featured: { title: "Successful Conference in Prague", excerpt: "Over 500 participants discussed the future of Czech-Slovak relations" }, business: { title: "New Partnerships Between Companies", excerpt: "15 new cooperation agreements signed" }, culture: { title: "Cultural Exchange Continues", excerpt: "New program for young artists" } },
    contact: { title: "Join the Initiative", subtitle: "Become part of our movement for a better future", volunteer: { title: "Volunteering", description: "Help us organize events and spread the idea of cooperation", button: "Become a Volunteer" }, donate: { title: "Support", description: "Financially support our activities and projects", button: "Donate" }, newsletter: { title: "Newsletter", description: "Get the latest information about our activities", button: "Subscribe" }, info: { title: "Contact Information", email: "Email", phone: "Phone", address: "Address" } },
    footer: { about: { title: "About Us", text: "Citizens' initiative for restoring natural bonds between the Czech Republic and Slovakia." }, links: { title: "Quick Links", about: "About", events: "Events", business: "Business", contact: "Contact" }, contact: { title: "Contact" }, map: { title: "Historic Czechoslovakia" }, rights: "All rights reserved." }
  }
} as const;

export const languages = Object.keys(translations) as (keyof typeof translations)[];
